sudo: false

language: python

python:
  - 3.6
  
install:
  - pip install -r api/requirements.txt
  - nvm install 0.8.12
  - npm install expo-cli --global

script:
  - cd api
  - python manage.py test api/test
